### PR TITLE
Use pluggable clock for auto refresh cache and make unit tests fast

### LINKED ISSUE #5711: [BUG] flytestdlib/cache unit tests are flaky
### Describe the bug

During a recent build in CI I encountered a unit test failure. I noticed that pluggable / test time sources aren't being used in thees unit tests which may lead to flakes depending on how slowly the unit tests are executed. It would be best to use a test time source instead, it will also speed up the tests because they won't have to sleep. 

```
--- FAIL: TestCacheFour (8.11s)
    --- FAIL: TestCacheFour/Test_panic_on_sync_and_shutdown (5.50s)
        auto_refresh_test.go:200: 
            	Error Trace:	/home/runner/work/flyte/flyte/flytestdlib/cache/auto_refresh_test.go:200
            	Error:      	Condition never satisfied
            	Test:       	TestCacheFour/Test_panic_on_sync_and_shutdown
        auto_refresh_test.go:208: 
            	Error Trace:	/home/runner/work/flyte/flyte/flytestdlib/cache/auto_refresh_test.go:208
            	Error:      	Not equal: 
            	            	expected: 10
            	            	actual  : 0
            	Test:       	TestCacheFour/Test_panic_on_sync_and_shutdown
```

### Expected behavior

The unit tests pass and are deterministic.

### Additional context to reproduce

_No response_

### Screenshots

_No response_

### Are you sure this issue hasn't been raised already?

- [X] Yes

### Have you read the Code of Conduct?

- [X] Yes

### PR DESCRIPTION
**Pull request by Sovietaced**
## Tracking issue
Closes #5711 

## Why are the changes needed?

Previously this unit test was relying on a real clock which makes unit tests slow and flaky due to nondeterministic execution duration. If code takes a dependency on time it should use a pluggable clock. 

Before 
```
ok      github.com/flyteorg/flyte/flytestdlib/cache     8.828s
```

After
```
ok      github.com/flyteorg/flyte/flytestdlib/cache     0.277s
```

## What changes were proposed in this pull request?
`autoRefresh` and the work queue it relies were updated to use a pluggable clock. A fake clock is used for unit tests while a real clock is used under all other circumstances.

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

### CODE REVIEW

File: flytestdlib/cache/auto_refresh_test.go [hunk 1]
```diff
@@ -167,24 +174,27 @@ func TestCacheFour(t *testing.T) {
 		})
 		assert.NoError(t, err)
 
-		// Wait half a second for all resync periods to complete
 		// If the cache tries to enqueue the item, a panic will be thrown.
-		time.Sleep(500 * time.Millisecond)
+		fakeClock.Step(testResyncPeriod)
```
Comment (Sovietaced) [inline flytestdlib/cache/auto_refresh_test.go:178]: These tests aren't perfect with how things are asynchronous... It's hard to verify that a sync actually happened. I wanted to add a unexpected sync counter to the auto refresh to use in unit tests but the constructor imo incorrectly returns the interface instead of a pointer to the struct (which should adhere to the interface). As such, the unit tests can't access anything package level.

Comment (Sovietaced) [reply flytestdlib/cache/auto_refresh_test.go:178]: I wanted to fix that but I'm trying to reduce the blast radius of this change.

File: flytestdlib/cache/auto_refresh.go [hunk 2]
```diff
@@ -406,3 +428,8 @@ func NewAutoRefreshCache(name string, syncCb SyncFunc, syncRateLimiter workqueue
 
 	return NewAutoRefreshBatchedCache(name, SingleItemBatches, syncCb, syncRateLimiter, resyncPeriod, parallelizm, size, scope)
 }
+
+func newAutoRefreshCacheWithClock(name string, syncCb SyncFunc, syncRateLimiter workqueue.RateLimiter, resyncPeriod time.Duration,
```
Comment (Sovietaced) [inline flytestdlib/cache/auto_refresh.go:432]: I've added these package lever constructors for testing but honestly with all the arguments that can be configured on the auto refresh cache it would be nicer to have a constructor with `Options`. I can follow up with that in another pull request if you'd like.

File: flytestdlib/cache/auto_refresh.go [hunk 3]
```diff
@@ -165,17 +166,29 @@ func (w *autoRefresh) Start(ctx context.Context) error {
 	}
 
 	enqueueCtx := contextutils.WithGoroutineLabel(ctx, fmt.Sprintf("%v-enqueue", w.name))
-
-	go wait.Until(func() {
```
Comment (Sovietaced) [inline flytestdlib/cache/auto_refresh.go:169]: Moved away from using `wait.Until` so I could use a pluggable clock.

File: flytestdlib/.golangci.yml [hunk 4]
```diff
@@ -26,7 +26,6 @@ linters:
     - structcheck
     - typecheck
     - unconvert
-    - unparam
```
Comment (Sovietaced) [inline flytestdlib/.golangci.yml:29]: Disabling since I was getting 
```
cache/auto_refresh.go:433:2: `newAutoRefreshCacheWithClock` - `parallelizm` always receives `10` (unparam)
        parallelizm, size int, scope promutils.Scope, clock clock.WithTicker) (AutoRefresh, error) {
        ^
```

I could omit this from my specific line but people generally seem to think this linter is pretty annoying.

File: flytestdlib/cache/auto_refresh.go (hunk 2 above)
Comment (eapolinario) [reply flytestdlib/cache/auto_refresh.go:432]: We can do that in a separate PR.

**Review by eapolinario — APPROVED** [review]
Thank you for working on this.
