### PR TITLE
fix: correct TaskAction CR/pod names and namespaces, improve run ID generation

### LINKED ISSUE #6969: [BUG] CR and Pod name is incorrect
### Flyte & Flytekit version

flyte v2

### Describe the bug

```
flyte                testorg-flytesnacks-development-run-1772749610-1p8occ60iefjh50slakm7y7fb   0/1     Completed   0             43m
flyte                testorg-flytesnacks-development-run-1772749610-1tsk1jutflj5rxm53pqwalhd2   0/1     Completed   0             43m
flyte                testorg-flytesnacks-development-run-1772749610-2dly0jqbp82npd9fop3r9onon   0/1     Completed   0             43m
flyte                testorg-flytesnacks-development-run-1772749610-2fhazqnjb2uhh2ti5pc7kqfsd   0/1     Completed   0             43m
flyte                testorg-flytesnacks-development-run-1772749610-2oxnw2tnrg8aogqkmsv58cvml   0/1     Completed   0             43m
flyte                testorg-flytesnacks-development-run-1772749610-5kd0aqsfvh5nm8wrggw4bi1qq   0/1     Completed   0             43m
flyte                testorg-flytesnacks-development-run-1772749610-5w0ikygc4cqyhodlj7pgkp3cd   0/1     Completed   0             43m
flyte                testorg-flytesnacks-development-run-1772749610-7aaqt02zet6ored9iiht2bljr   0/1     Completed   0             43m
flyte                testorg-flytesnacks-development-run-1772749610-8ek5mzlt9n9q71r20grgk2id9   0/1     Completed   0             43m
flyte                testorg-flytesnacks-development-run-1772749610-bdliuzkle5310g85zyvi031p9   0/1     Completed   0             43m
flyte                testorg-flytesnacks-development-run-1772749610-run-1772749610              0/1     Completed   0             43m
```

### Expected behavior

The parent action pod name should be <run-id>-a0-<attempt>
the sub action pod name should be <run-id>-<action-id>-0

Also, the pod should be created in flytesnacks-development namespace

### Additional context to reproduce

_No response_

### Screenshots

_No response_

### Are you sure this issue hasn't been raised already?

- [x] Yes

### Have you read the Code of Conduct?

- [x] Yes

### PR DESCRIPTION
**Pull request by AdilFayyaz**
## Tracking issue

Closes #6969

## Why are the changes needed?

Two bugs were causing TaskActions and pods to be created incorrectly:

1. Wrong names: CR and pod names included an {org}-{project}-{domain} prefix and the root action duplicated the run name, producing names like org-project-domain-runname-runname-0 instead of runname-a0-0.
2. Wrong namespace: TaskActions were created in the flyte namespace instead of the project-scoped {project}-{domain} namespace (e.g. flytetest-development).

Additionally, run IDs were generated with a time-based format (run-\<unix\_timestamp>) which is not suitable for production use.

## What changes were proposed in this pull request?

1. Fixed buildTaskActionName (actions/k8s/client.go): Root actions now produce {runName}-a0-0; child actions produce {runName}-{actionName}-0.
2. Fixed namespace derivation (actions/k8s/client.go): Added buildNamespace which computes {project}-{domain} from the run identifier. All CRUD operations and the watcher now use this namespace. The watcher watches all namespaces.
3. Auto-creates namespaces on demand (actions/k8s/client.go): Enqueue calls an injected ensureNamespace function before creating a TaskAction, so project-scoped namespaces are created automatically.
4. Improved run ID format (runs/service/run\_service.go): Run names are now generated as r<19 random chars> using k8s.io/apimachinery/pkg/util/rand.
5. Single source of run name generation (runs/service/run\_service.go, runs/repository/impl/action.go): The service generates the run name once and converts ProjectId → RunId before calling the repository, removing redundant name generation in the repo layer.
6. Moved EnsureNamespaceExists to flytestdlib/k8s (flytestdlib/k8s/namespace.go): Shared utility for idempotent namespace creation, used by both app/k8s.go and actions/setup.go.

## How was this patch tested?

Tested end-to-end using the local development setup (make run in manager/). A workflow was submitted via the SDK and verified that:

- TaskAction CRs were created in the correct flytesnacks-development namespace
- CR and pod names matched the expected format ({runName}-a0-0 for root, {runName}-{actionName}-0 for children)
- Run IDs followed the r<19chars> format

Also tested against unit tests:

- actions/k8s/client\_test.go — 4 tests
- runs/service/run\_service\_test.go — 4 tests

* `main` 
  - \#6583
    - \#6986 :point\_left:

### CODE REVIEW

File: actions/k8s/client.go [hunk 1]
```diff
@@ -75,10 +77,16 @@ func (c *ActionsClient) Enqueue(ctx context.Context, action *actions.Action, run
 	isRoot := action.ParentActionName == nil || *action.ParentActionName == ""
 
 	taskActionName := buildTaskActionName(actionID)
+	namespace := buildNamespace(actionID.Run)
+	if c.ensureNamespace != nil {
+		if err := c.ensureNamespace(ctx, namespace); err != nil {
```
Comment (pingsutw) [inline actions/k8s/client.go]: Can we just do `k8s.EnsureNamespaceExists(ctx, c.k8sClient, namespace)` here, so we don't need to pass `ensureNamespace` to ActionClient

Comment (AdilFayyaz) [reply actions/k8s/client.go]: updated!
