### PR TITLE
Fix: customize demo cluster port

### LINKED ISSUE #3792: [Flytectl Feature] flytectl demo cluster - configurable port number
**Problem Description:**

`flytectl demo start` command fails with below error when a developer has `Docker Desktop` which allows us to have a `Kubernetes` local cluster. Kubernetes API server runs on port `6443`. So we have to either turn off local Kubernetes cluster (not a good option) or allow demo cluster to use some other port.

```
{"status":"Status: Downloaded newer image for cr.flyte.org/flyteorg/flyte-sandbox-bundled:sha-1ae254f8683699b68ecddc89d775fc5d39cc3d84"}
🧑‍🏭 booting Flyte-sandbox container
😬 Something went wrong: Failed to start Sandbox container 🐋, Please check your docker client and try again. 
Error: Error response from daemon: driver failed programming external connectivity on endpoint flyte-sandbox (5eaf6609c86e6d818291e2f060e42f8002dfd4e288393da6e01109cfa5a60bd7): listen tcp4 0.0.0.0:6443: bind: address already in use
```

**Requested feature:**
Allow `demo` cluster to use other port preferrably via config file (config.yaml or config-sandbox.yaml or some other file) so that if a developer has some other container / process using the same port, they can change it and quickly get the demo cluster up and running.

**Environment details:**

- Docker Desktop with Kubernetes enabled
- Mac with M1 chip
- Discussion about this issue on slack is [here](https://flyte-org.slack.com/archives/CP2HDHKE1/p1687257726564769)

```
flytectl version  
{
  "App": "flytectl",
  "Build": "0cb2bfa",
  "Version": "0.6.39",
  "BuildTime": "2023-06-20 14:45:22.664715 +0200 CEST m=+0.016518584"
}

```

### PR DESCRIPTION
**Pull request by vincent0426**
## Tracking issue

Closes #3792 

## Why are the changes needed?
- As stated in #3792, when a developer uses Docker Desktop with Kubernetes running on port 6443, they must shut it down before running the demo cluster

- Allow users to configure the demo cluster port if needed

## What changes were proposed in this pull request?
1. Add a new parameter `port`, e.g., `flytectl demo start --port 6443`
2. Dynamically retrieve k8sEndpoint from `sandbox_config.go` instead of using fixed ones
3. Refactor `reload.go` to retrieve sandbox config (follow other file structure under `flyte/flytectl/cmd/demo`)

## How was this patch tested?
Tested that parameters were automatically generated with `make generate`

### Setup process
1. Run a k8s cluster that uses port 6443 (docker desktop k8s for testing)
2. Start the demo cluster without specifying port, which defaults to :6443 (expected to fail)
3. Start the demo cluster with port 6444
4. `kubectl --server=https://localhost:6444 get pods`
5. `export FLYTECTL_CONFIG= ~/<pathTo>/.flyte/config-sandbox.yaml`
6. Run the test with any `pyflyte run --remote`

### Screenshots
Screenshot 2024-11-07 at 10 58 51 AM

## Check all the applicable boxes 

- [X] I updated the documentation accordingly.
- [X] All new and existing tests passed.
- [X] All commits are signed-off.

### CODE REVIEW

**Comment by eapolinario** [comment]
Can you also modify the creation of the kubeconfig file to point to this new port? Trace uses of https://github.com/flyteorg/flyte/blob/master/flytectl/pkg/docker/docker_util.go#L31

As part of initializing the sandbox we write a kubeconfig file that simplifies access to the cluster.  That `kubeconfig` file lives under `~/.flyte/sandbox/`.

File: flytectl/cmd/config/subcommand/sandbox/sandbox_config.go [hunk 1]
```diff
@@ -36,9 +40,18 @@ type Config struct {
 	DryRun bool `json:"dryRun" pflag:",Optional. Only print the docker commands to bring up flyte sandbox/demo container.This will still call github api's to get the latest flyte release to use'"`
 
 	Force bool `json:"force" pflag:",Optional. Forcefully delete existing sandbox cluster if it exists."`
+
+	// Allow user to specify the port for the sandbox
+	Port string `json:"port" pflag:",Optional. Specify the port for the sandbox."`
```
Comment (pingsutw) [inline flytectl/cmd/config/subcommand/sandbox/sandbox_config.go:45]: nit
```suggestion
	Port string `json:"port" pflag:",Optional. Specify the port for the Kubernetes in the sandbox."`
```
