### PR TITLE
fix: Make datacatalog gRPC server MaxRecvMsgSize configurable

### LINKED ISSUE #6306: [BUG] Datacatalog does not provide a way to customize gRPC max receiving message size
### Describe the bug

When starting gRPC server of datacatalog, it is not possible to customize gRPC max receiving message size using `grpc.MaxRecvMsgSize`, which means for any artifact larger than 4MB, the server would reject it with `ResourceExhausted` error.

### Expected behavior

This value should be configurable with 4MB as default.

### Additional context to reproduce

_No response_

### Screenshots

_No response_

### Are you sure this issue hasn't been raised already?

- [x] Yes

### Have you read the Code of Conduct?

- [x] Yes

### PR DESCRIPTION
**Pull request by honnix**
## Tracking issue

Closes #6306

## Why are the changes needed?
It is possible that a task might upload an artifact larger than 4MB that is default value of MaxRecvMsgSize of gRPC server, and when that happens propeller would get a failed call. It feels reasonable to leave the choice to users.

## What changes were proposed in this pull request?

Make datacatalog gRPC server MaxRecvMsgSize configurable

## How was this patch tested?
Partially unit tested

### Labels

Please add one or more of the following labels to categorize your PR:
- **added**: For new features.
- **changed**: For changes in existing functionality.
- **deprecated**: For soon-to-be-removed features.
- **removed**: For features being removed.
- **fixed**: For any bug fixed.
- **security**: In case of vulnerabilities

This is important to improve the readability of release notes.

## Check all the applicable boxes 

- [x] I updated the documentation accordingly.
- [x] All new and existing tests passed.
- [x] All commits are signed-off.

## Docs link

 
 <div id='description'>
<h3>Summary by Bito</h3>
This PR makes gRPC MaxReceiveMessageSize configurable by introducing 'grpcMaxRecvMsgSizeMBs' parameter in chart and configuration files. It enables the datacatalog gRPC server to handle larger artifact uploads without failure. Deployment templates and Docker manifests have been updated to ensure consistency across environments.
<br>
<br>
<b>Unit tests added</b>: False
<br>
<br>
<b>Estimated effort to review (1-5, lower is better)</b>: 3
</div>

### CODE REVIEW

File: datacatalog/pkg/config/config_flags.go [hunk 1]
```diff
@@ -52,6 +52,7 @@ func (cfg Config) GetPFlagSet(prefix string) *pflag.FlagSet {
 	cmdFlags := pflag.NewFlagSet("Config", pflag.ExitOnError)
 	cmdFlags.Int(fmt.Sprintf("%v%v", prefix, "grpcPort"), defaultConfig.GrpcPort, "On which grpc port to serve Catalog")
 	cmdFlags.Bool(fmt.Sprintf("%v%v", prefix, "grpcServerReflection"), defaultConfig.GrpcServerReflection, "Enable GRPC Server Reflection")
+	cmdFlags.Int(fmt.Sprintf("%v%v", prefix, "grpcMaxRecvMsgSizeMBs"), defaultConfig.GrpcMaxRecvMsgSizeMBs, "The max receive message size; if unset defaults to gRPC server default value")
```
Comment (honnix) [inline datacatalog/pkg/config/config_flags.go:55]: I actually modified this manually because `make generate` didn't work for me.
```
Installing github.com/vektra/mockery/v2@v2.40.3
go: github.com/vektra/mockery/v2@v2.40.3 (in github.com/vektra/mockery/v2@v2.40.3): go.mod:5: unknown directive: toolchain
```

Comment (honnix) [reply datacatalog/pkg/config/config_flags.go:55]: I think something is not working well with goenv.

Comment (honnix) [reply datacatalog/pkg/config/config_flags.go:55]: I had to use `goenv shell`.

Comment (honnix) [reply datacatalog/pkg/config/config_flags.go:55]: Proposed a minor fix in #6314

**Review by eapolinario — COMMENTED** [review]
Can you also expose this in the flyte-core and flyte-binary charts?

**Comment by honnix** [comment]
> Can you also expose this in the flyte-core and flyte-binary charts?

I did some changes in the last commit. Please let me know if I did something wrong or missed some. I'm not familiar with these things. Thank you.

**Review by eapolinario — APPROVED** [review]

**Comment by eapolinario** [comment]
Thank you!
