### PR TITLE
fix: flyteadmin doesn't shutdown servers gracefully

### LINKED ISSUE #6274: [BUG] Flyte Admin Should Terminate Gracefully
### Describe the bug

Flyte Admin does not appear to respond to SIGTERM and as such does not gracefully terminate when Kubernetes is doing a rolling restart or upgrade. Servers should terminate gracefully so that they can drain buffers, connections, RPCs, etc and minimize errors or loss of data. 

### Expected behavior

When receiving a SIGTERM, I expect Flyte Admin to run a shutdown sequence where the RPC servers are shut down and any buffers are drained. 

### Additional context to reproduce

_No response_

### Screenshots

_No response_

### Are you sure this issue hasn't been raised already?

- [x] Yes

### Have you read the Code of Conduct?

- [x] Yes

### PR DESCRIPTION
**Pull request by lowc1012**
## Tracking issue
Closes #6274 

## Why are the changes needed?
To handle SIGTERM properly, ensure cleanup of resources and provide smooth user experience

## What changes were proposed in this pull request?
Implement graceful shutdown for flyteadmin servers

### Labels

Please add one or more of the following labels to categorize your PR:
- **added**: For new features.
- **changed**: For changes in existing functionality.
- **deprecated**: For soon-to-be-removed features.
- **removed**: For features being removed.
- **fixed**: For any bug fixed.
- **security**: In case of vulnerabilities

This is important to improve the readability of release notes.

## Check all the applicable boxes 

- [ ] I updated the documentation accordingly.
- [ ] All new and existing tests passed.
- [x] All commits are signed-off.

## Docs link

 
 <div id='description'>
    <a href="https://bito.ai#summarystart"></a>
<h3>Summary by Bito</h3>
This pull request enhances the flyteadmin servers by implementing a graceful shutdown mechanism with a configurable timeout for resource cleanup. It also improves error handling during gRPC server startup, enhancing overall service reliability.

</div>

### CODE REVIEW

**Comment by eapolinario** [comment]
@lowc1012 , is this ready for review?

**Comment by lowc1012** [comment]
@eapolinario please help review it, thank you

**Comment by Sovietaced** [comment]
> @eapolinario please help review it, thank you

I was the original one that filed this issue for myself to take a look at later so I can review it a bit.

File: flyteadmin/pkg/server/service.go [hunk 1]
```diff
@@ -422,11 +426,35 @@ func serveGatewayInsecure(ctx context.Context, pluginRegistry *plugins.Registry,
...
 	}
 
+	grpcShutdownCtx, grpcCancel := context.WithTimeout(context.Background(), 10*time.Second)
+	defer grpcCancel()
+
+	go func() {
+		grpcServer.GracefulStop()
+		grpcCancel()
+	}()
+	<-grpcShutdownCtx.Done()
```
Comment (Sovietaced) [inline flyteadmin/pkg/server/service.go:455]: Waiting for graceful shutdown doesn't necessarily mean that it completed successful graceful shutdown. We should follow up with a more forceful stop per the documentation/examples: https://github.com/grpc/grpc-go/blob/master/examples/features/gracefulstop/server/main.go#L93-L99

**Comment by Sovietaced** [comment]
Part of my thinking when handling graceful shutdown was not just the servers but also draining any buffers, specifically for cloud events so that we minimize notifications that are dropped because they are still buffered in memory.

**Comment by Sovietaced** [comment]
> Part of my thinking when handling graceful shutdown was not just the servers but also draining any buffers, specifically for cloud events so that we minimize notifications that are dropped because they are still buffered in memory.

I think the buffers might have been in my company's custom fork but it would still be good to look for anything else that can be drained or shutdown via context after the servers are shutdown.

File: flyteadmin/pkg/server/service.go [hunk 2]
```diff
@@ -422,11 +426,35 @@ func serveGatewayInsecure(ctx context.Context, pluginRegistry *plugins.Registry,
...
-		return errors.Wrapf(err, "failed to Start HTTP Server")
+	go func() {
+		err = server.ListenAndServe()
+		if err != nil && err != http.ErrServerClosed {
+			logger.Fatalf(ctx, "Failed to start HTTP Server: %v", err)
+		}
+	}()
+
+	// Gracefully shutdown the servers
+	sigCh := make(chan os.Signal, 1)
```
[the remark this answers is not in the document]
Comment (lowc1012) [reply flyteadmin/pkg/server/service.go:437]: you mean just `SIGINT` or `SIGTERM`?

[the remark this answers is not in the document]
Comment (Sovietaced) [reply flyteadmin/pkg/server/service.go:437]: I mean that in this diff you have two signal channels. You only need one to know whether or not the app is shutting down.

File: flyteadmin/pkg/server/service.go [hunk 3]
```diff
@@ -422,11 +426,34 @@ func serveGatewayInsecure(ctx context.Context, pluginRegistry *plugins.Registry,
...
+	signal.Notify(sigCh, syscall.SIGINT, syscall.SIGTERM)
+	<-sigCh
+	time.Sleep(1 * time.Second)
```
Comment (Sovietaced) [inline flyteadmin/pkg/server/service.go:440]: Not sure we need this sleep.

File: flyteadmin/pkg/server/service.go [hunk 4]
```diff
@@ -422,11 +426,34 @@ func serveGatewayInsecure(ctx context.Context, pluginRegistry *plugins.Registry,
...
+
+	// force to shut down servers after 10 seconds
+	timer := time.AfterFunc(10 * time.Second, func() {
```
Comment (Sovietaced) [inline flyteadmin/pkg/server/service.go:443]: May want to make this timeout configurable

Comment (lowc1012) [reply flyteadmin/pkg/server/service.go:443]: Like configure the timeout in flyteadmin_config.yaml?

```
server:
  forceShutdownTimeoutSec: 10

Comment (Sovietaced) [reply flyteadmin/pkg/server/service.go:443]: Yeah. Something along those lines.

Comment (lowc1012) [reply flyteadmin/pkg/server/service.go]: updated

File: flyteadmin/pkg/server/service.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (Sovietaced) [reply flyteadmin/pkg/server/service.go:438]: Is it possible to trigger graceful shutdown off of a single signal listener? After that I think this pull request is good to merge.

[the remark this answers is not in the document]
Comment (lowc1012) [reply flyteadmin/pkg/server/service.go:438]: @Sovietaced updated, thank you

**Comment by Sovietaced** [comment]
@lowc1012 can you sign off your commits?

**Comment by lowc1012** [comment]
> @lowc1012 can you sign off your commits?

done

File: flyteadmin/pkg/server/service.go (hunk 2 above)
[the remark this answers is not in the document]
Comment (Sovietaced) [reply flyteadmin/pkg/server/service.go:438]: Oh I see, you have one for each method.

**Review by Sovietaced — APPROVED** [review]
